### ISSUE TITLE
짱 !!

### ISSUE THREAD

**Issue by insungok** [App-plePi/StressFit#1]
* Package 이름은 소문자로 네이밍하는것을 권장합니다.

* MainActivity 44~66 번째 줄 같은 
if문은 when문으로 설정하는것을 권장합니다.
when문이 훨씬 더 코드가 간결해지고, 가독성을 높일 수 있습니다. 

* 변수의 네이밍은 카멜 케이스, 파스칼 케이스, 스네이크 케이스 중 하나를 선택하여 네이밍 하는것를 권장합니다.
https://velog.io/@leyuri/%ED%91%9C%EA%B8%B0%EB%B2%95-%EC%8A%A4%EB%84%A4%EC%9D%B4%ED%81%AC-%EC%BC%80%EC%9D%B4%EC%8A%A4-%ED%8C%8C%EC%8A%A4%EC%B9%BC-%EC%BC%80%EC%9D%B4%EC%8A%A4-%EC%B9%B4%EB%A9%9C-%EC%BC%80%EC%9D%B4%EC%8A%A4
를 참고해보세요!

* Image는 png로 사용하는 것 보다 svg를 사용하는것을 권장합니다. (svg는 반응형이라 이미지가 깨지지않음)

* 앱에서 웹사이트를 띄울 때 Intent를 이용한 방법도 있습니다. 
https://hello-bryan.tistory.com/m/126
을 참고해보세용

* 전체 코드를 드래그 하여 Ctrl+ Alt + L 키를 누르면 코드를 정리할 수 있습니다.

**Comment by 2tle** [comment]
png이슈 제외한 나머지 부분 어느정도 수정 완료했습니다.
